//=============================================================================
//
// Code generated by [VAPS XT 4.2.1]
//
//=============================================================================

#ifndef VXTCLSOPENGLTRIANGLEPLUGIN_H
#define VXTCLSOPENGLTRIANGLEPLUGIN_H

//=============================================================================
//                        I N C L U D E   F I L E S
//=============================================================================

#include "sqxPlugin.h"

#include "vxtClsOpenGLTriangle.h"

extern "C" VXTCLSOPENGLTRIANGLE_SPEC sqxPlugin * sqxPluginLoad(void); 

extern "C" VXTCLSOPENGLTRIANGLE_SPEC const vxtChar * sqxPluginProductAPIVersion(void); 


//=============================================================================
//                                C L A S S
//=============================================================================

class VXTCLSOPENGLTRIANGLE_SPEC vxtClsOpenGLTrianglePlugin : public sqxPlugin
{
public:

   vxtClsOpenGLTrianglePlugin(const vxtChar *, vxtFloat);

   virtual ~vxtClsOpenGLTrianglePlugin();

   virtual vxtBool Initialize(void*);

   virtual void vCleanUp(void*);

   static vxtRTObject* s_pCreateRTObject(const void* a_pInitData);

   static void s_vDeleteRTObject(vxtRTObject* a_pObject);

private:

   // Disallow copy
   vxtClsOpenGLTrianglePlugin( const vxtClsOpenGLTrianglePlugin& );
   vxtClsOpenGLTrianglePlugin& operator=( const vxtClsOpenGLTrianglePlugin& );
};


#endif // VXTCLSOPENGLTRIANGLEPLUGIN_H

// END OF FILE

